
# 학습할 것
- 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
- 자바가 제공하는 예외 계층 구조
- Exception과 Error의 차이는?
- RuntimeException과 RE가 아닌 것의 차이는?
- 커스텀한 예외 만드는 방법

---

>먼저 에러란 ?   
프로그램 실행 중 어떤 원인에 의해 오작동하거나 비정상 종료된 경우.   
이를 **초래하는 원인**을 프로그램 에러 또는 오류 라고 한다.
   
발생 시점에 따라 컴파일 에러 Compile Error, 런타임 에러 Runtime Error 로 나눌 수 있다.   
외에도 논리적 에러 Logical Error가 있다.   

- 컴파일 에러
말 그대로 컴파일 시(실행 전) 발생하는 에러.  
- 런타임 에러
프로그램 실행 도중 발생하는 에러.  
- 논리적 에러
컴파일도 잘 되고, 실행도 잘 되지만 의도한 것과 다르게 동작하는 에러.  

소스를 컴파일하면 컴파일러가 소스코드(*.java)에 대해 오타나 자료형 체크 등 기본검사를 수행하여 오류를 알려준다.   
컴파일러가 알려준 에러들을 모두 수정해서 컴파일을 성공적으로 하면,   
클래스파일(*.class)이 생성되고 생성된 클래스 파일을 실행할 수 있게 된다.   

컴파일러가 소스코드의 기본적 사항은 걸러줄 수 있지만 실행도중 발생하는 잠재적 오류(런타임 에러)까지 검사할 수는 없다.   

런타임 에러를 방지하기 위해서는 프로그램의 실행도중 발생할 수 있는 모든 경우의 수를 고려하여 대비해야 한다. 자바에서는 실행시(runtime) 발생할 수 있는 프로그램 오류를 에러 error 와 예외 exception 두 가지로 구분한다.   

https://cheershennah.tistory.com/144


---
# 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)

```java
try {

  //예외발생할 가능성이 있는 문장 

  }catch(Exception1 e1) {

   //Exception1이 발생했을 경우, 이를 처리하지 위한 문장적는다.
   //보통 이곳에 예외메세지를 출력하고 로그로 남김.

  }catch(Exception2 e2) {

   //Exception2이 발생했을 경우, 이를 처리하지 위한 문장적는다.

  }catch(ExceptionN eN) {

   //ExceptionN이 발생했을 경우, 이를 처리하지 위한 문장적는다.

  }finally{

  //예외발생여부에 관계없이 상항 수행되어야 하는 문장적는다.

}
```

마지막 finally 는 try-catch 문과 함께 예외발생 여부와 관계없이 "항상, 무조건" 실행되어야 하는 코드를 적는다.   
필수는 아니며 마지막에 선택적으로 덧붙여 사용한다.   

예외 발생시 try->catch->finally 순으로,   
발생하지 않은 경우 try->finally 순으로 실행.   

> finally 블록은 언제 사용할까?   
보통은 자원이나 DB에 커넥션 한 경우, 파일 정리, 연결 닫기(close) 등과 같은 "정리"코드를 넣는 데 사용한다.
   
Catch에서 처리하고자 하는 Exception 과 참조변수 e 를 선언한다.   
예외발생 시 발생예외에 해당하는 클래스의 인스턴스가 만들어진다.   
예를 들어 AuthException이 발생했다면 AuthException 인스턴스가 만들어진다.   

* printStackTrace()
예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메세지를 콘솔화면에 출력한다. 리턴값이 없고 가장 자세한 예외결과를 화면에 출력한다.
   

* throw e
예외 던지기(발생시키기).  
throw 키워드를 사용하여 프로그래머가 고의로 예외를 발생시킬 수 있다.   
try 안에서 new 연산자로 발생시키려는 예외클래스의 객체를 생성하여 키워드 throw를 통해 생성한 예외를 catch로 던진다.

```java
public static void main (String[] args) {
    try {
        Exception e = new Exception("고의발생"); // 1. 예외 생성
        throw e; // 2. 예외 던지기 
    } catch (Exception e) {
        System.out.println("에러메세지:" + e.getMessage());
        e.printStackTrace(); //예외정보 출력 
    }
    System.out.println("프로그램 정상 종료.");
}
```
```
에러메세지: 고의발생

java.lang.Exception: 고의발생
     at ExceptionEx9.main(ExceptionEx9.java:4)
     
프로그램 정상 종료.
```

---

# 자바가 제공하는 예외계층구조

![](https://velog.velcdn.com/images/jiwon709/post/36504b64-2d21-4baf-9b2e-7217109d0f87/image.png)

모두 Throwable을 상속하고 있으며, 여기서부터 Error와 Exception 발생.   
여기서 모든 예외의 조상은 모두 Exception이다.
   
예외 클래스들은 2개의 그룹으로 나눌 수 있는데.  
- RuntimeException 클래스와 그 자손 클래스
-> 주로 프로그래머의 실수에서 발생될 수 있는 예외들.  
- Exception 클래스와 그 자손 클래스
-> 외부의 영향, 프로그램의 사용자에 의해 발생.  

---

# Exception과 Error의 차이는?


>Error.  
프로그램 코드에 의해서 수습될 수 없는 심각한 오류.  
메모리 부족이나 스택오버플로우와 같이 발생하면 복구할 수 없는 심각한 오류.  

>Exception.  
프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류.  
발생하더라도 수습할 수 있는 비교적 덜 심각한 오류.  

좀 더 보자면,   

- Error : 컴파일 시 **문법적인 오류** , 런타임 시 **널포인트 참조와 같은 오류**로 프로세스에 심각한 문제를 야기 시켜 프로세스를 종료 가능

- Exception : 컴퓨터 시스템의 동작 도중 **예기치 않았던 이상 상태가 발생**하여 수행 중인 프로그램이 영향을 받는 것.   
예를 들면, 연산 도중 넘침에 의해 발생한 끼어들기 등이 이에 해당한다.

  
- 오류?
프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우를 프로그램 오류라고 한다.   
프로그램오류에는 에러(error)와 예외(exception) 두 가지로 구분할 수 있고, 위에서 말한 에러와 예외가 이에 대한 설명이다.   
  
 Error의 상황을 미리 미연에 방지하기 위해서 Exception 상황을 만들 수 있다. java에서는 try-catch문으로 Exception handling을 할 수 있다.

---

# RuntimeException과 RE가 아닌 것의 차이는?

위의 예외계층구조 에서 2가지의 그룹을 나눴었는데   

예외 클래스들은 2개의 그룹으로 나눌 수 있는데  
- RuntimeException 클래스와 그 자손 클래스
-> 주로 프로그래머의 실수에서 발생될 수 있는 예외들   
- Exception 클래스와 그 자손 클래스   
-> 외부의 영향, 프로그램의 사용자에 의해 발생

첫 번째 그룹을 Checked Exception.  
두 번째 그룹을 Uncheked Exception.   
으로 판단,    

Checked Exception : 반드시 예외를 처리.  
Unchecked Exception : 예외처리를 강제 하지 않는다.   

RuntimeException은 런타임 시에 예외를 발생시키며, 실행 전에는 컴파일 에러를 발생시키지 않는다. 즉, Unchecked Exception   
예외처리를 강제하지는 않지만 해당 내용이 런타임 시에 예외를 발생시킬 수 있음을 인지하면 예외 처리를 해주는게 좋다.   

RuntimeException 대표적 예
- NullPointException
- IndexOutOfBoundsException
- ArithmeticException

![](https://velog.velcdn.com/images/jiwon709/post/1adfb66b-4d30-41ea-bd49-91ec09ea3742/image.png)

어떠한 정수를 0으로 나눈다고 한다면   
컴파일 단계에서는 에러가 발생하지 않지만 런타임 단계에서 에러가 발생한다.   
Unchecked Exception.  

그 외 클래스들은 Checked Exception으로   
실행하기 전 컴파일 단계에서 에러를 발생시킨다. 실행 전 반드시 예외처리 필요
   
대표적 예
- IOException
- SQLException
   
BufferedReader 타입의 객체로 입력받는 경우, 데이터를 모두 읽은 후에 종료해야 한다.
   
![](https://velog.velcdn.com/images/jiwon709/post/ce0fd35d-6454-49af-9db1-e1d141794ee5/image.png)

close를 하면 컴파일 시 IOException 발생하는 것을 볼 수 있다. 즉, CheckedException.
   
- IOException?   
Input, Output Exception
   

- bufferedReader란?   
https://m.blog.naver.com/ka28/221850826909


---

# 커스텀한 예외 만드는 방법
   
자바의 상속을 만들어서 처리를 하면 된다는데   
다른 사람의 스터디 발표내용 참고 후, 다시 작성하도록 하겠다.   

---

참고사이트
   
https://cheershennah.tistory.com/147
   
https://velog.io/@new_wisdom/Exception
   
https://staticclass.tistory.com/69
   
https://drcarter.tistory.com/153
   
https://velog.io/@zayson/%EB%B0%B1%EA%B8%B0%EC%84%A0%EB%8B%98%EA%B3%BC-%ED%95%A8%EA%BB%98%ED%95%98%EB%8A%94-Live-Study-9%EC%A3%BC%EC%B0%A8-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC#-runtimeexception%EA%B3%BC-re%EA%B0%80-%EC%95%84%EB%8B%8C-%EA%B2%83%EC%9D%98-%EC%B0%A8%EC%9D%B4%EB%8A%94
